apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: /.kube/MyChart-0.1.0.tgz
        digests:
            chart: sha256:dce4906ffbbd961006ec41a2f9525a05e10c4015ac183183aedfd1bddbf2cfc5
            package: 81cb622ea9615bf239ab62e29a1d6a78c1200cfa4073b3acd373337515107d1f
        lastCertifiedTimestamp: "2022-12-21T12:26:40.632052+00:00"
        testedOpenShiftVersion: N/A
        supportedOpenShiftVersions: N/A
        providerControlledDelivery: false
    chart:
        name: MyChart
        home: ""
        sources: []
        version: 0.1.0
        description: A Helm chart for Kubernetes
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.16.0
        deprecated: false
        annotations: {}
        kubeversion: ""
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: FAIL
      reason: Kubernetes version is not specified
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: FAIL
      reason: 'Chart Install failure: release name "MyChart-bjpxm7eoli": invalid release name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 53'
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: FAIL
      reason: Values schema file does not exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: FAIL
      reason: Chart does not have a README
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: FAIL
      reason: |-
        Image is not Red Hat certified : nginx:1.16.0 : Respository not found: nginx
        Image is not Red Hat certified : busybox : Respository not found: busybox
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: FAIL
      reason: 'Missing required annotations: [charts.openshift.io/name]'