apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        profile:
            VendorType: redhat
            version: v1.1
        chart-uri: /.kube/mysql-sed-0.2.1.tgz
        digests:
            chart: sha256:2d566642d2ddd247ade7197435db2b34f47f38352250795ae67bcea6840e4cbf
            package: dfb888845e4d3a9f9ef7e2954ecd96b811b9f7c31498d32e74ccc0476fe8aec7
        lastCertifiedTimestamp: "2022-11-04T02:57:28.186761+00:00"
        testedOpenShiftVersion: "4.11"
        supportedOpenShiftVersions: '>=4.7'
        providerControlledDelivery: false
    chart:
        name: mysql-sed
        home: ""
        sources: []
        version: 0.2.1
        description: A Helm chart for MySQL Service Endpoint Definition (SED)
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 0.1.0
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: MYSQL Service Endpoint Definition (SED)
            charts.openshift.io/provider: RedHat
            charts.openshift.io/supportURL: https://github.com/redhat-developer/service-endpoint-definition
        kubeversion: '>=1.20.0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: 'Image is Red Hat certified : registry.access.redhat.com/rhscl/mysql-80-rhel7:latest'
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist